### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by banyan** [quipper/sbpayment.rb#3]
* [x] Change client to request class
* [x] Create response class which knows decode
* [x] Retry
* [x] Consider link type to build parameters for JS (client side)
* [x] <del>Validator</del> 
 * Parameters from users are limited. won't implement it.
* [x] How to order to build attributes
